import openpyxl
import pathlib
import os
import datetime
import pymysql
from google.cloud.sql.connector import connector
import sqlalchemy
from datetime import datetime
from AIFinanceBEL import Person, ResponseDTO

class DBBase(object):
    """description of class"""
    def __init__(self):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "ai-financial-coop202112-6120926f2230.json"
        self.__Pool =sqlalchemy.create_engine("mysql+pymysql://", creator = self.__getconn,)


    def __getconn(self) -> pymysql.connections.Connection:
        # Set MySQL connection info
        _MySQL_connectionName = 'ai-financial-coop202112:us-central1:hengyi'
        _MySQL_host = '35.225.4.226'
        _MySQL_user = 'AIF0013'
        _MySQL_password = 'LiXie-AIF'
        _MySQL_database = 'aif_db_AIF0013'

        conn : pymysql.connections.Connection = connector.connect(
            _MySQL_connectionName,
            "pymysql",
            user= _MySQL_user,
            password = _MySQL_password,
            db = _MySQL_database,
            autocommit = True
            #cafile=MySQL_SSLPath,
            #validate_host=False,
        )
        return conn

class AIFinanceDB(DBBase):
    
    def SavePerson(self, p: Person) -> ResponseDTO:
        _resp = ResponseDTO()
        with self._DBBase__Pool.connect() as db_conn:       
            insert_stmt = sqlalchemy.text("call test_usp(:p1 , @x)", )
            rproxy = db_conn.execute(insert_stmt,  p1 = p.FullName)
            result = db_conn.execute('SELECT @x').fetchone()

            if p.LastName == "Qi":
                p.PersonID  = 43
                _resp.ErrorCode = 0
            else:
                p.PersonID  = 44
                _resp.ErrorCode = 99

            _resp.ErrorMsg = 'Failed to save ' + result[0]          
        
        return _resp